[32m2022-09-01 11:30:26.319[0m | [31m[1mERROR   [0m | [36m__main__[0m:[36mmain[0m:[36m38[0m - [31m[1mAn error has been caught in function 'main', process 'MainProcess' (1263675), thread 'MainThread' (140677153195840):[0m
[33m[1mTraceback (most recent call last):[0m

  File "[32m/home/gr/k8s-nodeport-mtd/[0m[32m[1madversary.py[0m", line [33m42[0m, in [35m<module>[0m
    [1mmain[0m[1m([0m[1m)[0m
    [36mâ”” [0m[36m[1m<function main at 0x7ff1f298c310>[0m

> File "[32m/home/gr/k8s-nodeport-mtd/[0m[32m[1madversary.py[0m", line [33m38[0m, in [35mmain[0m
    [1mprint[0m[1m([0m[1mperform_port_scan[0m[1m([0m[36m"10.2.255.1"[0m[1m)[0m[1m)[0m
    [36m      â”” [0m[36m[1m<function perform_port_scan at 0x7ff1f2977520>[0m

  File "[32m/home/gr/k8s-nodeport-mtd/[0m[32m[1madversary.py[0m", line [33m12[0m, in [35mperform_port_scan[0m
    [35m[1mif[0m [1mname[0m[1m([0m[1m)[0m [35m[1m!=[0m [36m"posix"[0m[1m:[0m
    [36m   â”” [0m[36m[1m'posix'[0m

[31m[1mTypeError[0m:[1m 'str' object is not callable[0m
[32m2022-09-01 13:17:38.166[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mupdate[0m:[36m37[0m - [32m[1mAll services patched. Legit app is exposed on app-service3 NodePort now[0m
[32m2022-09-01 13:17:38.191[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mupdate[0m:[36m43[0m - [32m[1m{'app-service1': 32186, 'app-service2': 31827, 'app-service3': 32707, 'app-service4': 31776, 'app-service5': 32385}[0m
[32m2022-09-01 13:22:31.044[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m63[0m - [32m[1mSuccessfully exploited app at 10.2.255.1:32707[0m
[32m2022-09-01 13:23:05.377[0m | [1mINFO    [0m | [36m__main__[0m:[36mmain[0m:[36m54[0m - [1mTarget IP is set to 10.2.255.1[0m
[32m2022-09-01 13:23:05.591[0m | [1mINFO    [0m | [36m__main__[0m:[36mmain[0m:[36m56[0m - [1mOpen ports are: [30043, 31776, 31827, 32186, 32351, 32385, 32707][0m
[32m2022-09-01 13:23:05.632[0m | [1mINFO    [0m | [36m__main__[0m:[36mmain[0m:[36m58[0m - [1mLegitimate app found at 32707[0m
[32m2022-09-01 13:23:15.654[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m63[0m - [32m[1mSuccessfully exploited app at 10.2.255.1:32707[0m
[32m2022-09-01 13:23:15.655[0m | [1mINFO    [0m | [36m__main__[0m:[36mmain[0m:[36m54[0m - [1mTarget IP is set to 10.2.255.1[0m
[32m2022-09-01 13:23:15.844[0m | [1mINFO    [0m | [36m__main__[0m:[36mmain[0m:[36m56[0m - [1mOpen ports are: [30043, 31776, 31827, 32186, 32351, 32385, 32707][0m
[32m2022-09-01 13:23:15.881[0m | [1mINFO    [0m | [36m__main__[0m:[36mmain[0m:[36m58[0m - [1mLegitimate app found at 32707[0m
[32m2022-09-01 13:25:08.825[0m | [1mINFO    [0m | [36m__main__[0m:[36mmain[0m:[36m56[0m - [1mTarget IP is set to 10.2.255.1[0m
[32m2022-09-01 13:25:09.030[0m | [1mINFO    [0m | [36m__main__[0m:[36mmain[0m:[36m58[0m - [1mOpen ports are: [30043, 31776, 31827, 32186, 32351, 32385, 32707][0m
[32m2022-09-01 13:25:09.076[0m | [1mINFO    [0m | [36m__main__[0m:[36mmain[0m:[36m60[0m - [1mLegitimate app found at 32707[0m
[32m2022-09-01 13:25:19.096[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m68[0m - [32m[1mSuccessfully exploited app at 10.2.255.1:32707[0m
[32m2022-09-01 13:25:19.097[0m | [32m[1mSUCCESS [0m | [36m__main__[0m:[36mmain[0m:[36m69[0m - [32m[1msuccessful_exploits=1[0m
[32m2022-09-01 13:25:19.097[0m | [1mINFO    [0m | [36m__main__[0m:[36mmain[0m:[36m56[0m - [1mTarget IP is set to 10.2.255.1[0m
[32m2022-09-01 13:25:19.312[0m | [1mINFO    [0m | [36m__main__[0m:[36mmain[0m:[36m58[0m - [1mOpen ports are: [30043, 31776, 31827, 32186, 32351, 32385, 32707][0m
[32m2022-09-01 13:25:19.358[0m | [1mINFO    [0m | [36m__main__[0m:[36mmain[0m:[36m60[0m - [1mLegitimate app found at 32707[0m
